In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from functools import partial

import kornia

use_cuda = torch.cuda.is_available()
device = torch.device('cuda' if use_cuda else 'cpu')


In [2]:
print(device)

cpu


In [3]:
a=torch.arange(0,6).view(2,3)
b=a.unsqueeze(0)
print(b)

tensor([[[0, 1, 2],
         [3, 4, 5]]])


In [4]:
a = torch.arange(0, 6).view(2, 3)
b = a.unsqueeze(1)
print(b)


tensor([[[0, 1, 2]],

        [[3, 4, 5]]])


In [5]:
Gx = torch.tensor([[-1.0, 0.0, 1.0], [-1.0, 0.0, 1.0], [-1.0, 0.0, 1.0]]) / 3
Gy = torch.tensor(
    [[1.0, 1.0, 1.0], [0.0, 0.0, 0.0], [-1.0, -1.0, -1.0]]) / 3
G = torch.cat([Gx.unsqueeze(0), Gy.unsqueeze(0)], 0)
print(Gx.unsqueeze(0).size())
G = G.unsqueeze(1)
print(G.size())


torch.Size([1, 3, 3])
torch.Size([2, 1, 3, 3])


In [6]:
filter = nn.Conv2d(in_channels=1, out_channels=2,
                   kernel_size=3, stride=1, padding=0, bias=False)
Gx = torch.tensor([[-1.0, 0.0, 1.0], [-1.0, 0.0, 1.0], [-1.0, 0.0, 1.0]]) / 3
Gy = torch.tensor(
    [[1.0, 1.0, 1.0], [0.0, 0.0, 0.0], [-1.0, -1.0, -1.0]]) / 3
G = torch.cat([Gx.unsqueeze(0), Gy.unsqueeze(0)], 0)  # 得到一个2x3x3的矩阵
G = G.unsqueeze(1).to(device)
filter.weight = nn.Parameter(
    G, requires_grad=False)  # requires_grad是否需要计算中保留其对应需要的梯度信息
print(filter.weight.size())

torch.Size([2, 1, 3, 3])


In [7]:
t_0=torch.randn(3,3)
t_1=torch.ones_like(t_0)


In [8]:
t_0

tensor([[-0.4244,  0.8458, -0.9639],
        [ 2.5282, -1.0004,  1.1721],
        [ 0.9093, -0.6292,  0.3186]])

In [9]:
t_1

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [10]:
torch.mul(t_0,t_1)

tensor([[-0.4244,  0.8458, -0.9639],
        [ 2.5282, -1.0004,  1.1721],
        [ 0.9093, -0.6292,  0.3186]])

In [11]:
X = torch.sum(t_0, dim=0, keepdim=True)
print(X)
X.size()


tensor([[ 3.0131, -0.7838,  0.5268]])


torch.Size([1, 3])

In [12]:
ff=torch.mean(t_0,dim=1,keepdim=True)

In [13]:
ff.size(-1)

1

In [33]:
input = torch.tensor([[1, 1, 1, 1, 1], [1, 1, 1, 1, 1], [0, 0, 0, 1, 1], [
                     1, 1, 1, 1, 1], [1, 1, 1, 1, 1]]).unsqueeze(0).float()
print(input.shape)
print(input)
m = F.avg_pool1d(input, kernel_size=2)
print(m)



torch.Size([1, 5, 5])
tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [0., 0., 0., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])
tensor([[[1.0000, 1.0000],
         [1.0000, 1.0000],
         [0.0000, 0.5000],
         [1.0000, 1.0000],
         [1.0000, 1.0000]]])


In [34]:
for i in range(4):
    print(i)

0
1
2
3
