In [17]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from functools import partial

import kornia

from math import exp

use_cuda = torch.cuda.is_available()
device = torch.device('cuda' if use_cuda else 'cpu')


In [2]:
print(device)

cpu


In [3]:
a=torch.arange(0,6).view(2,3)
b=a.unsqueeze(0)
print(b)

tensor([[[0, 1, 2],
         [3, 4, 5]]])


In [4]:
a = torch.arange(0, 6).view(2, 3)
b = a.unsqueeze(1)
print(b)


tensor([[[0, 1, 2]],

        [[3, 4, 5]]])


In [5]:
Gx = torch.tensor([[-1.0, 0.0, 1.0], [-1.0, 0.0, 1.0], [-1.0, 0.0, 1.0]]) / 3
Gy = torch.tensor(
    [[1.0, 1.0, 1.0], [0.0, 0.0, 0.0], [-1.0, -1.0, -1.0]]) / 3
G = torch.cat([Gx.unsqueeze(0), Gy.unsqueeze(0)], 0)
print(Gx.unsqueeze(0).size())
G = G.unsqueeze(1)
print(G.size())


torch.Size([1, 3, 3])
torch.Size([2, 1, 3, 3])


In [6]:
filter = nn.Conv2d(in_channels=1, out_channels=2,
                   kernel_size=3, stride=1, padding=0, bias=False)
Gx = torch.tensor([[-1.0, 0.0, 1.0], [-1.0, 0.0, 1.0], [-1.0, 0.0, 1.0]]) / 3
Gy = torch.tensor(
    [[1.0, 1.0, 1.0], [0.0, 0.0, 0.0], [-1.0, -1.0, -1.0]]) / 3
G = torch.cat([Gx.unsqueeze(0), Gy.unsqueeze(0)], 0)  # 得到一个2x3x3的矩阵
G = G.unsqueeze(1).to(device)
filter.weight = nn.Parameter(
    G, requires_grad=False)  # requires_grad是否需要计算中保留其对应需要的梯度信息
print(filter.weight.size())

torch.Size([2, 1, 3, 3])


In [7]:
t_0=torch.randn(3,3)
t_1=torch.ones_like(t_0)


In [8]:
t_0

tensor([[-1.1836,  1.6058, -0.5238],
        [ 0.7790, -0.4548, -1.0345],
        [-1.2927,  1.2370,  0.4749]])

In [9]:
t_1

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [10]:
torch.mul(t_0,t_1)

tensor([[-1.1836,  1.6058, -0.5238],
        [ 0.7790, -0.4548, -1.0345],
        [-1.2927,  1.2370,  0.4749]])

In [11]:
X = torch.sum(t_0, dim=0, keepdim=True)
print(X)
X.size()


tensor([[-1.6974,  2.3881, -1.0833]])


torch.Size([1, 3])

In [12]:
ff=torch.mean(t_0,dim=1,keepdim=True)

In [13]:
ff.size(-1)

1

In [14]:
input = torch.tensor([[1, 1, 1, 1, 1], [1, 1, 1, 1, 1], [0, 0, 0, 1, 1], [
                     1, 1, 1, 1, 1], [1, 1, 1, 1, 1]]).unsqueeze(0).float()
print(input.shape)
print(input)
m = F.avg_pool1d(input, kernel_size=2)
print(m)



torch.Size([1, 5, 5])
tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [0., 0., 0., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])
tensor([[[1.0000, 1.0000],
         [1.0000, 1.0000],
         [0.0000, 0.5000],
         [1.0000, 1.0000],
         [1.0000, 1.0000]]])


In [34]:
for i in range(4):
    print(i)

0
1
2
3


In [23]:
w=10 
s=1 
X=exp(-(2-w//2)**2/float(2*s**2))
gauss=torch.Tensor([exp(-(x-w//2)**2)/float(2*s**2) for x in range(w)])
print(gauss.shape)
print(gauss.sum())
g=gauss/gauss.sum()

torch.Size([10])
tensor(0.8863)


In [25]:
d1=g.unsqueeze(1)
d1.shape

torch.Size([10, 1])

In [27]:
a=torch.Tensor(torch.randn(10))
print(a)
b=a*a 
print(b)

tensor([ 0.2125, -1.2121, -0.9563, -1.5846,  1.0147, -0.2858,  0.4981,  0.9599,
        -0.9528,  0.6813])
tensor([0.0452, 1.4692, 0.9146, 2.5110, 1.0297, 0.0817, 0.2481, 0.9214, 0.9079,
        0.4642])
